version: '3.7'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./deploy/dockerfiles/Dockerfile
    volumes:
      - '.:/app/client'
      - '/app/client/node_modules'
    ports:
      - '3000:8080'